# Generated by Django 3.2.7 on 2021-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='imagecontainer')),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
